config/routes.rb
Rails.application.routes.draw do
  resources :variants
  resources :products
  resources :categories
  resources :product_searches
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #get "categories", to: "categories#index"
  #get "products", to: "products#index"
  #get "variants", to: "variants#index"

  #get "categories/:id", to: "categories#show"
  #get "products/:id", to: "products#show"
  #get "variants/:id", to: "variants#show"
  # get ...., to ..
  # post ... to ...
  # put ... to ..
  # delete ... to...
  #
  # get "categories/*id", to: 'categories#show'
  #
  # #api
  # namespace 'api' do
  #   namespace 'v1' do
  #     resources :categories
  #   end
  # end
  #
  # namespace 'api' do
  #   namespace 'v1' do
  #     resources :categories
  #   end
  # end
  #
  # namespace 'api' do
  #   namespace 'v1' do
  #     resources :products
  #   end
  # end
  #
  # get "api/v1/categories/*id", to: 'api/v1/categories#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  extend FriendlyId

  friendly_id :name, use: :slugged, slug_column: :slug_url

  has_many :products, class_name: "Product"

  validates :name, presence: true
  validates :state, presence: true
  validates :description, presence: true
  validates :state, inclusion: { in: %w(draft published discontinued) }


end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId

  friendly_id :label, use: :slugged, slug_column: :slug_url

  scope :root, -> { where(parent_id: nil) }

  belongs_to :parent, class_name: "Category", required: false
  has_many :subcategories, class_name: "Category", foreign_key: :parent_id
  has_many :products

  validates :label, presence: true
  validates :state, presence: true
  validates :state, inclusion: { in: %w(draft published discontinued) }

  def descendents
    subcategories.map do |subcategory|
      [subcategory] + subcategory.descendents
    end.flatten
  end

end

app/models/product.rb
class Product < ApplicationRecord
  extend FriendlyId

  friendly_id :name, use: :slugged, slug_column: :slug_url

  belongs_to :category, class_name: "Category", foreign_key: "category_id"
  has_many :variants, class_name: "Variant"
  belongs_to :brands, class_name: "Brand", foreign_key: "brand_id"

  validates :name, presence: true
  validates :state, presence: true
  validates :description, presence: true
  validates :state, inclusion: { in: %w(draft published discontinued) }


end

app/models/product_search.rb
class ProductSearch

  attr_reader :products

  def initialize
    # @products = Product.scope
  end

  def search(params)

    @products = Product.where(["name LIKE ?", "%#{params[:keywords]}%"]) if params.dig(:keywords).present?
    @products = @products.where(["category_id = ?", params[:parent]]) if params.dig(:parent).present?
    @products = Product.all unless @products

    self

  end

  def sort_by(sort_by)
    @products = @products.order(sort_by) if sort_by.present?
    self
  end


end

app/models/variant.rb
class Variant < ApplicationRecord
  belongs_to :product, class_name: "Product", foreign_key: "product_id"


  validates :name, presence: true
  validates :sold_out, inclusion: { in: [true,false]}
  validates :under_sale, inclusion: { in: [true,false]}
  validates :price, presence: true

  validates :sale_price, presence: true, if: :under_sale
  validates :sale_price, numericality: {less_than: :price}, if: :under_sale


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.order('label')

    include_hash = {
        include: params[:include]&.split(',')
    }.compact
    render json: CategorySerializer.new(@categories, include_hash).serialized_json
  end

  def show
    @category = Category.friendly.find(params[:id])

    include_hash = {
        include: params[:include]&.split(',')
    }.compact
    render json: CategorySerializer.new(@category, include_hash).serialized_json
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index

    if params[:page]
      if params[:page] == ""
        page = 1
      else
        page = params[:page]
      end
    else
      page = 1
    end

    if params[:size]
      if params[:size] == ""
        size = 3
      else
        size = params[:size]
      end
    else
      size = 3
    end


    if params[:sort_by]
      if params[:sort_by] == ""
        sort_by = 'name'
      else
        sort_by = params[:sort_by]
      end
    else
      sort_by = 'name'
    end

    @product_search = ProductSearch.new
    include_array = params[:include]&.split(',')

    @product_search.search(params).sort_by(sort_by)
    @products = @product_search.products.eager_load(include_array).paginate(page: page, per_page: size)
    # @categories = Category.all


    include_hash = {
        include: include_array
    }.compact

    render json: ProductSerializer.new(@products, include_hash).serialized_json
  end

  def show
    @product = Product.friendly.find(params[:id])

    include_hash = {
        include: params[:include]&.split(',')
    }.compact

    render json: ProductSerializer.new(@product, include_hash).serialized_json
  end
end

app/controllers/variants_controller.rb
class VariantsController < ApplicationController
  def index
    @variants = Variant.all

    include_hash = {
        include: params[:include]&.split(',')
    }.compact

    render json: VariantSerializer.new(@variants, include_hash).serialized_json
  end

  def show
    @variant = Variant.find(params[:id])
    @product = @variant.product

    include_hash = {
        include: params[:include]&.split(',')
    }.compact
    render json: VariantSerializer.new(@variant, include_hash).serialized_json
  end

  def new
    @variant = Variant.new
  end

  def edit
    @variant = Variant.find(params[:id])
  end

  def create
    @variant = Variant.new(variant_params)
    @product = @variant.product
    if @variant.save
      flash[:success] = "Successfully edited & updated variant"
      redirect_to @variant

    else
      puts @variant.errors.full_messages
      render 'new'

    end

  end

  def update
    @variant = Variant.find(params[:id])
    if @variant.update_attributes(variant_params)
      "Successful update"
    else
      render 'edit'
    end
  end


  def destroy
    @variant = Variant.find(params[:id])
    @variant.destroy

    redirect_to variants_path
  end


  private

  def variant_params
    params.require(:variant).permit(:name, :sold_out, :under_sale, :price, :sale_price, :sale_text, :product_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_controller_helper.rb
module CategoriesControllerHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/variants_helper.rb
module VariantsHelper
end

app/views/brands/_form.html.erb
<%= form_with(model: brand, local: true) do |form| %>
  <% if brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing Brand</h1>

<%#= render 'form', product: @product %>
<%= form_for @brand do |b| %>
  Name: <%= b.text_field :name %><br/>
  Description: <%= b.text_area :description %><br/>
  State: <%= b.text_field :state %><br/>
  <%= b.submit %>
<% end %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Brands</h1>

<table>
  <tbody>
  <% @brands.each do |brand| %>
    <tr>
      <td><%= link_to brand.name, brand %></td>
      <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
      <td><%= link_to 'Destroy', brand, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @brands %>
<%= link_to 'New Brand', new_brand_path %>
<%= link_to 'Brands', brands_path %>

app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= simple_form_for @brand do |f| %>
  <%= f.input :name %> <br>
  <%= f.input :description %> <br>
  State <br>
  <%= f.select :state, ['published', 'draft', 'discontinued'] %> <br> <br>
  <%= f.button :submit %>
<% end %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <tbody>
  <% @brand.products.each do |product| %>
    <tr>
      <% if product.sold_out %>
        <td><%= link_to product.name, product %> [SOLD OUT]</td>
        <td><%= link_to 'Edit', edit_category_path(product) %></td>
        <td><%= link_to 'Destroy', variant, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      <% else %>
        <td><%= link_to variant.name, variant %></td>
        <td><%= link_to 'Edit', edit_category_path(variant) %></td>
        <td><%= link_to 'Destroy', variant, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      <% end %>
    </tr>
  <% end %>
  <% if @product.variants.first == nil %>
    There are no variants right now!
  <% end %>
  </tbody>
</table>

<%= link_to 'New Variant', new_variant_path %> |
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %> |
<%= link_to 'Products', products_path %>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%#= render 'form', category: @category %>

<%= form_for @category do |c| %>
  Label: <%= c.text_field :label %><br/>
  State: <%= c.text_field :state %><br/>
  <%= c.submit %>
<% end %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <% if category.parent == nil %>
        <tr>
          <td><%= link_to category.label, category %></td>
          <td><%= link_to 'Edit', edit_category_path(category) %></td>
          <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>
<%= link_to 'Back', categories_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%#= render 'form', category: @category %>

<%= simple_form_for @category do |c| %>
  <%= c.input :label %> <br>
  State:
  <%= c.select :state, ['published', 'draft', 'discontinued'] %> <br> <br>
  <%= c.association :parent, label_method: :label, include_blank: true %> <br>
  <%= c.button :submit %>
<% end %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <tbody>
  <% @category.subcategories.each do |subcategory| %>
    <tr>
      <td><%= link_to subcategory.label, subcategory %></td>
      <td><%= link_to 'Edit', edit_category_path(subcategory) %></td>
      <td><%= link_to 'Destroy', subcategory, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<table>
  <tbody>
  <% @category.products.each do |product| %>
    <tr>
      <% if product.variants.size == 1 %>
        <td><%= link_to product.variants.first.name, product.variants.first %></td>
        <td><%= link_to 'Edit', edit_variant_path(product.variants.first) %></td>
        <td><%= link_to 'Destroy', product.variants.first, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      <% else %>
        <td><%= link_to product.name, product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      <% end %>
    </tr>
  <% end %>
  <% if (@category.subcategories.first == nil) && (@category.products.first == nil) %>
    There are no products right now!
  <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %> |
<%= link_to 'New Product', new_product_path %> |

<br>
<br>

<%= link_to 'Main Categories', categories_path %> |
<%= link_to 'Products', products_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Research</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/product_searches/new.html.erb
<h1> Products Search </h1>

<%= form_tag(products_path, method: :get) do%>
  <%= text_field_tag :keywords %>
  <%= submit_tag 'Search' %>

<% end %>
<table>
  <thead>
  <tr>
    <th colspan="3"></th>
  </tr>
  </thead>  <tbody>
  <% @products.each do |product| %>
    <tr>
      <td><%= link_to product.name, product %></td>
      <td><%= link_to 'Edit', edit_product_path(product) %></td>
      <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>

</table>
<p>
  <% link_to 'Back', products_path %></p>

app/views/product_searches/show.html.erb
<h1>Search Results</h1>

<p><%= link_to 'Back', new_product_search_path %></p>
<%= link_to 'Products', products_path %>

<% if @product_search.search.empty? %>
  <p>No Records Found</p>
<% else %>
  <% @product_search.search.each do |product| %>
    <br>

    <div class="div">
      <td><%= link_to product.name, product %></td>
      <td><%= link_to 'Edit', edit_product_path(product) %></td>
      <td><%= link_to 'Destroy', product, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </div>

  <% end %>
<% end %>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%#= render 'form', product: @product %>
<%= form_for @product do |p| %>
  Name: <%= p.text_field :name %><br/>
  Description: <%= p.text_area :description %><br/>
  State: <%= p.text_field :state %><br/>
  <%= p.submit %>
<% end %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<%= form_tag products_path, :method => "get" do %>
  Keywords
  <%= text_field_tag :keywords, params[:keywords] %>
  Sort By
  <%= select_tag :sort_by, options_for_select(['id', 'name', 'description']) %>
  Category
  <%= select_tag :parent, options_from_collection_for_select(@categories, 'id', 'label'), :include_blank => true %>
  Page
  <%= text_field_tag :page, params[:page], :include_blank => false %>
  Products per Page
  <%= text_field_tag :size, params[:size], :include_blank => false %>
  <%= submit_tag "Search" %>
<% end %>

<p/>

<table>
  <thead>
  <tr>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @products.each do |product| %>
    <tr>
      <td><%= link_to product.name, product %></td>
      <td><%= link_to 'Edit', edit_product_path(product) %></td>
      <td><%= link_to 'Destroy', product, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @products %>
<%= link_to 'New Product', new_product_path %>
<%= link_to 'Categories', categories_path(@categories) %>
<%= link_to 'Products', products_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%#= render 'form', product: @product %>

<%= simple_form_for @product do |f| %>
  <%= f.input :name %> <br>
  <%= f.input :description %> <br>
  State <br>
  <%= f.select :state, ['published', 'draft', 'discontinued'] %> <br> <br>
  <%= f.association :category, label_method: :label, value_method: :id, include_blank: false %> <br>
  <%= f.button :submit %>
<% end %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <tbody>
  <% @product.variants.each do |variant| %>
    <tr>
      <% if variant.sold_out %>
        <td><%= link_to variant.name, variant %> [SOLD OUT]</td>
        <td><%= link_to 'Edit', edit_category_path(variant) %></td>
        <td><%= link_to 'Destroy', variant, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      <% else %>
        <td><%= link_to variant.name, variant %></td>
        <td><%= link_to 'Edit', edit_category_path(variant) %></td>
        <td><%= link_to 'Destroy', variant, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      <% end %>
    </tr>
  <% end %>
  <% if @product.variants.first == nil %>
    There are no variants right now!
  <% end %>
  </tbody>
</table>

<%= link_to 'New Variant', new_variant_path %> |
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %> |
<%= link_to 'Products', products_path %>

app/views/shared/_nav.html.erb
<%= simple_form_for @variant do |v| %>
  <%= v.input :name %> <br>
  Sold out?
  <%= v.select :sold_out, [true, false] %> <br>
  On sale?
  <%= v.select :under_sale, [true, false] %> <br>
  <%= v.input :price %> <br>
  <%= v.input :sale_price %> <br>
  <%= v.input :sale_text %> <br>
  <%= v.association :product, label_method: :name, include_blank: false %> <br>
  <%= v.button :submit %>
<% end %>

app/views/variants/_form.html.erb
<%= form_with(model: variant, local: true) do |form| %>
  <% if variant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(variant.errors.count, "error") %> prohibited this variant from being saved:</h2>

      <ul>
      <% variant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/variants/edit.html.erb
<h1>Editing Variant</h1>

<%#= render 'form', variant: @variant %>

<% # app/views/posts/edit.html.erb %>

<%= form_for @variant do |v| %>
  Name: <%= v.text_field :name %><br/>
  Sold out?: <%= v.text_field :sold_out %><br/>
  On sale?: <%= v.text_field :under_sale %><br/>
  Original price: <%= v.text_field :price %><br/>
  Sale price: <%= v.text_field :sale_price %><br/>
  Sale text: <%= v.text_area :sale_text %><br/>
  <%= v.submit %>
<% end %>

<%= link_to 'Show', @variant %> |
<%= link_to 'Back', variants_path %>

app/views/variants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Variants</h1>

<table>
  <thead>
  <tr>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @variants.each do |variant| %>
    <tr>
      <td><%= link_to variant.name, variant %></td>
      <td><%= link_to 'Edit', edit_variant_path(variant) %></td>
      <td><%= link_to 'Destroy', variant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Variant', new_variant_path %> |
<%= link_to 'Main Categories', categories_path %> |
<%= link_to 'Products', products_path %>

app/views/variants/new.html.erb
<h1>New Variant</h1>

<%#= render 'form', variant: @variant %>
<%= render "shared/nav" %>



<%= link_to 'Back', variants_path %>

app/views/variants/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <tbody>
  <% if @variant.sold_out %>
    Sorry! <%= @variant.name %> is <strong> sold out </strong>. Try another?
  <% else %>
    The product is <strong><%= @product.name %></strong>
    <div/>
    Variant is <strong><%= @variant.name %> </strong>
    <tr></tr>
    <div/>
    Description: <span style="color:#3b607a"> <%= @product.description %> </span>
    <div/>
    Price:
    <% if @variant.under_sale %>
      <del><%= sprintf("$%2.2f", @variant.price / 100.00) %></del>
      <span style="color:#ff184b"><%= sprintf("$%2.2f", (@variant.sale_price / 100.00)) %></span>
    <% else %>
      <%= sprintf("$%2.2f", @variant.price / 100.00) %>
    <% end %>
  <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_variant_path(@product) %> |
<%= link_to 'Back', product_path(@product) %>